[tool.poetry]
name = "fmpxx"
version = "0.2.1"
description = ""
authors = ["ron <wu.kong@foxmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"
python-dotenv = "^1.0.1"
retry = "^0.9.2"
pandas = "1.5.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
